/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/app'
import { Route as AttendantRouteImport } from './routes/attendant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAvailabilityRouteImport } from './routes/app/availability'
import { Route as AppOccupancyRouteImport } from './routes/app/occupancy'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppOverrideRouteImport } from './routes/app/override'
import { Route as AppPermitsRouteImport } from './routes/app/permits'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppReservationsRouteImport } from './routes/app/reservations'
import { Route as AppSetupRouteImport } from './routes/app/setup'
import { Route as AppStaffRouteImport } from './routes/app/staff'
import { Route as AttendantIndexRouteImport } from './routes/attendant/index'
import { Route as AttendantActiveRouteImport } from './routes/attendant/active'
import { Route as BookFacilityIdRouteImport } from './routes/book/$facilityId'
import { Route as CheckinBookingCodeRouteImport } from './routes/checkin/$bookingCode'
import { Route as MyReservationsRouteImport } from './routes/my/reservations'
import { Route as MySettingsRouteImport } from './routes/my/settings'
import { Route as AppBookingManifestRouteImport } from './routes/app/booking/manifest'
import { Route as AppFacilitiesIndexRouteImport } from './routes/app/facilities/index'
import { Route as AppFacilitiesFacilityIdRouteImport } from './routes/app/facilities/$facilityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendantRoute = AttendantRouteImport.update({
  id: '/attendant',
  path: '/attendant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const AppOccupancyRoute = AppOccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOverrideRoute = AppOverrideRouteImport.update({
  id: '/override',
  path: '/override',
  getParentRoute: () => AppRoute,
} as any)
const AppPermitsRoute = AppPermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AttendantIndexRoute = AttendantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttendantRoute,
} as any)
const AttendantActiveRoute = AttendantActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AttendantRoute,
} as any)
const BookFacilityIdRoute = BookFacilityIdRouteImport.update({
  id: '/book/$facilityId',
  path: '/book/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinBookingCodeRoute = CheckinBookingCodeRouteImport.update({
  id: '/checkin/$bookingCode',
  path: '/checkin/$bookingCode',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReservationsRoute = MyReservationsRouteImport.update({
  id: '/my/reservations',
  path: '/my/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MySettingsRoute = MySettingsRouteImport.update({
  id: '/my/settings',
  path: '/my/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookingManifestRoute = AppBookingManifestRouteImport.update({
  id: '/booking/manifest',
  path: '/booking/manifest',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilitiesIndexRoute = AppFacilitiesIndexRouteImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => AppRoute,
} as any)
const AppFacilitiesFacilityIdRoute = AppFacilitiesFacilityIdRouteImport.update({
  id: '/facilities/$facilityId',
  path: '/facilities/$facilityId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/attendant': typeof AttendantRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/occupancy': typeof AppOccupancyRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/override': typeof AppOverrideRoute
  '/app/permits': typeof AppPermitsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/staff': typeof AppStaffRoute
  '/attendant/active': typeof AttendantActiveRoute
  '/book/$facilityId': typeof BookFacilityIdRoute
  '/checkin/$bookingCode': typeof CheckinBookingCodeRoute
  '/my/reservations': typeof MyReservationsRoute
  '/my/settings': typeof MySettingsRoute
  '/app/': typeof AppIndexRoute
  '/attendant/': typeof AttendantIndexRoute
  '/app/booking/manifest': typeof AppBookingManifestRoute
  '/app/facilities/$facilityId': typeof AppFacilitiesFacilityIdRoute
  '/app/facilities/': typeof AppFacilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/occupancy': typeof AppOccupancyRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/override': typeof AppOverrideRoute
  '/app/permits': typeof AppPermitsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/staff': typeof AppStaffRoute
  '/attendant/active': typeof AttendantActiveRoute
  '/book/$facilityId': typeof BookFacilityIdRoute
  '/checkin/$bookingCode': typeof CheckinBookingCodeRoute
  '/my/reservations': typeof MyReservationsRoute
  '/my/settings': typeof MySettingsRoute
  '/app': typeof AppIndexRoute
  '/attendant': typeof AttendantIndexRoute
  '/app/booking/manifest': typeof AppBookingManifestRoute
  '/app/facilities/$facilityId': typeof AppFacilitiesFacilityIdRoute
  '/app/facilities': typeof AppFacilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/attendant': typeof AttendantRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/app/availability': typeof AppAvailabilityRoute
  '/app/occupancy': typeof AppOccupancyRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/override': typeof AppOverrideRoute
  '/app/permits': typeof AppPermitsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/staff': typeof AppStaffRoute
  '/attendant/active': typeof AttendantActiveRoute
  '/book/$facilityId': typeof BookFacilityIdRoute
  '/checkin/$bookingCode': typeof CheckinBookingCodeRoute
  '/my/reservations': typeof MyReservationsRoute
  '/my/settings': typeof MySettingsRoute
  '/app/': typeof AppIndexRoute
  '/attendant/': typeof AttendantIndexRoute
  '/app/booking/manifest': typeof AppBookingManifestRoute
  '/app/facilities/$facilityId': typeof AppFacilitiesFacilityIdRoute
  '/app/facilities/': typeof AppFacilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/app'
    | '/attendant'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/app/availability'
    | '/app/occupancy'
    | '/app/onboarding'
    | '/app/override'
    | '/app/permits'
    | '/app/reports'
    | '/app/reservations'
    | '/app/setup'
    | '/app/staff'
    | '/attendant/active'
    | '/book/$facilityId'
    | '/checkin/$bookingCode'
    | '/my/reservations'
    | '/my/settings'
    | '/app/'
    | '/attendant/'
    | '/app/booking/manifest'
    | '/app/facilities/$facilityId'
    | '/app/facilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/app/availability'
    | '/app/occupancy'
    | '/app/onboarding'
    | '/app/override'
    | '/app/permits'
    | '/app/reports'
    | '/app/reservations'
    | '/app/setup'
    | '/app/staff'
    | '/attendant/active'
    | '/book/$facilityId'
    | '/checkin/$bookingCode'
    | '/my/reservations'
    | '/my/settings'
    | '/app'
    | '/attendant'
    | '/app/booking/manifest'
    | '/app/facilities/$facilityId'
    | '/app/facilities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-invite'
    | '/app'
    | '/attendant'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/app/availability'
    | '/app/occupancy'
    | '/app/onboarding'
    | '/app/override'
    | '/app/permits'
    | '/app/reports'
    | '/app/reservations'
    | '/app/setup'
    | '/app/staff'
    | '/attendant/active'
    | '/book/$facilityId'
    | '/checkin/$bookingCode'
    | '/my/reservations'
    | '/my/settings'
    | '/app/'
    | '/attendant/'
    | '/app/booking/manifest'
    | '/app/facilities/$facilityId'
    | '/app/facilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AppRoute: typeof AppRouteWithChildren
  AttendantRoute: typeof AttendantRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  BookFacilityIdRoute: typeof BookFacilityIdRoute
  CheckinBookingCodeRoute: typeof CheckinBookingCodeRoute
  MyReservationsRoute: typeof MyReservationsRoute
  MySettingsRoute: typeof MySettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendant': {
      id: '/attendant'
      path: '/attendant'
      fullPath: '/attendant'
      preLoaderRoute: typeof AttendantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/availability': {
      id: '/app/availability'
      path: '/availability'
      fullPath: '/app/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/occupancy': {
      id: '/app/occupancy'
      path: '/occupancy'
      fullPath: '/app/occupancy'
      preLoaderRoute: typeof AppOccupancyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/override': {
      id: '/app/override'
      path: '/override'
      fullPath: '/app/override'
      preLoaderRoute: typeof AppOverrideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/permits': {
      id: '/app/permits'
      path: '/permits'
      fullPath: '/app/permits'
      preLoaderRoute: typeof AppPermitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/attendant/': {
      id: '/attendant/'
      path: '/'
      fullPath: '/attendant/'
      preLoaderRoute: typeof AttendantIndexRouteImport
      parentRoute: typeof AttendantRoute
    }
    '/attendant/active': {
      id: '/attendant/active'
      path: '/active'
      fullPath: '/attendant/active'
      preLoaderRoute: typeof AttendantActiveRouteImport
      parentRoute: typeof AttendantRoute
    }
    '/book/$facilityId': {
      id: '/book/$facilityId'
      path: '/book/$facilityId'
      fullPath: '/book/$facilityId'
      preLoaderRoute: typeof BookFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$bookingCode': {
      id: '/checkin/$bookingCode'
      path: '/checkin/$bookingCode'
      fullPath: '/checkin/$bookingCode'
      preLoaderRoute: typeof CheckinBookingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/reservations': {
      id: '/my/reservations'
      path: '/my/reservations'
      fullPath: '/my/reservations'
      preLoaderRoute: typeof MyReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/settings': {
      id: '/my/settings'
      path: '/my/settings'
      fullPath: '/my/settings'
      preLoaderRoute: typeof MySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/booking/manifest': {
      id: '/app/booking/manifest'
      path: '/booking/manifest'
      fullPath: '/app/booking/manifest'
      preLoaderRoute: typeof AppBookingManifestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/facilities/': {
      id: '/app/facilities/'
      path: '/facilities'
      fullPath: '/app/facilities/'
      preLoaderRoute: typeof AppFacilitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/facilities/$facilityId': {
      id: '/app/facilities/$facilityId'
      path: '/facilities/$facilityId'
      fullPath: '/app/facilities/$facilityId'
      preLoaderRoute: typeof AppFacilitiesFacilityIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppOccupancyRoute: typeof AppOccupancyRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOverrideRoute: typeof AppOverrideRoute
  AppPermitsRoute: typeof AppPermitsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppStaffRoute: typeof AppStaffRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookingManifestRoute: typeof AppBookingManifestRoute
  AppFacilitiesFacilityIdRoute: typeof AppFacilitiesFacilityIdRoute
  AppFacilitiesIndexRoute: typeof AppFacilitiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppOccupancyRoute: AppOccupancyRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOverrideRoute: AppOverrideRoute,
  AppPermitsRoute: AppPermitsRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppSetupRoute: AppSetupRoute,
  AppStaffRoute: AppStaffRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookingManifestRoute: AppBookingManifestRoute,
  AppFacilitiesFacilityIdRoute: AppFacilitiesFacilityIdRoute,
  AppFacilitiesIndexRoute: AppFacilitiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AttendantRouteChildren {
  AttendantActiveRoute: typeof AttendantActiveRoute
  AttendantIndexRoute: typeof AttendantIndexRoute
}

const AttendantRouteChildren: AttendantRouteChildren = {
  AttendantActiveRoute: AttendantActiveRoute,
  AttendantIndexRoute: AttendantIndexRoute,
}

const AttendantRouteWithChildren = AttendantRoute._addFileChildren(
  AttendantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AppRoute: AppRouteWithChildren,
  AttendantRoute: AttendantRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  BookFacilityIdRoute: BookFacilityIdRoute,
  CheckinBookingCodeRoute: CheckinBookingCodeRoute,
  MyReservationsRoute: MyReservationsRoute,
  MySettingsRoute: MySettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
